version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: job_recommendation_db
    restart: always
    environment:
      POSTGRES_DB: job_recommendation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
